// https://github.com/gauravghongde/social-icons
export const socialIcons = [
  'apple.svg',
  'assistantapps.svg',
  'behance.svg',
  'discord.svg',
  'epic.svg',
  'eisvana.png',
  'facebook.svg',
  'github.svg',
  'instagram.svg',
  'medium.svg',
  'nintendo.svg',
  'nmsassistant.png',
  'patreon.svg',
  'paypal.svg',
  'play.google.svg',
  'playstation.svg',
  'qq.svg',
  'reddit.svg',
  'sony.svg',
  'spotify.svg',
  'steam.svg',
  'tiktok.svg',
  'twitch.svg',
  'twitter.svg',
  'vine.svg',
  'wechat.svg',
  'weibo.svg',
  'whatsapp.svg',
  'x.svg',
  'xbox.svg',
  'youtube.svg',
] as const;
