// Generated by Xata Codegen 0.28.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "community",
    columns: [
      { name: "name", type: "string" },
      { name: "profilePic", type: "string" },
      { name: "bio", type: "string" },
      { name: "bioMediaUrls", type: "string" },
      { name: "tags", type: "string" },
      { name: "socials", type: "string" },
      { name: "contactDetails", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Community = InferredTypes["community"];
export type CommunityRecord = Community & XataRecord;

export type DatabaseSchema = {
  community: CommunityRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://support-s-workspace-9tmlv0.eu-central-1.xata.sh/db/nmsud-submission",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
