name: CommitMessageCheck
run-name: Commit Message Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: main

concurrency:
  group: 'checkcommit'
  cancel-in-progress: true

jobs:
  check-commit-message:
    environment: github-pages
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.CHECK_COMMIT_GITHUB_TOKEN }}

      - name: WIP notice
        run: echo "This is WIP (work in progress)"

      - name: Check PR commits
        run: |
          commits = ${{ steps.get-pr-commits.outputs.commits }}
          for value in "${commits[@]}"
          do
            echo "Value for item array is: $value"
          done

      - name: Post PR Comment
        if: failure()
        uses: mshick/add-pr-comment@v2
        with:
          message: Please check the commit messages in this PR! It seems that you have not used emojis, this is a requirement for this project as per our documentation (https://nmsud-form-docs.nmsassistant.com) 
          refresh-message-position: true
          allow-repeats: true
