name: Github Pages
run-name: GithubPages

on:
  push:
    branches: ['main']

concurrency:
  group: 'githubpages'
  cancel-in-progress: true

jobs:
  githubpages:
    name: Github Pages
    environment: github-pages
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install npm packages
        run: npm ci

      - name: Setup variables
        env:
          WEB_UI_CONFIG: ${{ secrets.WEB_UI_CONFIG }}
        run: |
          touch .env
          echo WEB_UI_CONFIG >> .env

      - name: Build web UI
        run: |
          npm run build:web
          touch ./dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
