name: TestBuild
run-name: Test Build

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

concurrency:
  group: 'githubpages'
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install npm packages
        run: npm ci

      - name: Run tests
        run: npm run test
